/** Shared catalog — used by seed script */
const PRODUCT_CATALOG = [
  {
    name: 'Onix Smart Mining Glasses Pro',
    description:
      'Flagship HUD eyewear with dust sealing, shift-long comfort, and fleet-ready diagnostics. IP-rated frame for underground crews.',
    price: 2499,
    compareAtPrice: 3299,
    category: 'Smart Mining Glasses',
    imageUrl: '/images/50746b80-92c1-420b-9bcc-a37fea89c3bd.jpg',
    stock: 48,
    badge: 'Bestseller',
    rating: 4.9,
    reviewCount: 128,
  },
  {
    name: 'NightVision Pro Mining Glasses',
    description:
      'Low-light optimized lenses for night shifts and dim tunnel work. Includes hardened case and anti-fog insert.',
    price: 3199,
    compareAtPrice: 3999,
    category: 'Smart Mining Glasses',
    imageUrl: '/images/0a64963e-298b-4da8-88ff-9fcb856db7be.jpg',
    stock: 32,
    badge: 'Pro',
    rating: 4.8,
    reviewCount: 86,
  },
  {
    name: 'Navigator Z1 Smart Lens',
    description:
      'Entry-level connected eyewear with blue-light filtering and voice-assist ready temples.',
    price: 499,
    compareAtPrice: 799,
    category: 'Smart Mining Glasses',
    imageUrl: '/images/sec3.jpg',
    stock: 210,
    badge: 'Value',
    rating: 4.6,
    reviewCount: 214,
  },
  {
    name: 'Onix Terra HUD X2',
    description:
      'Dual-display smart frame with environmental sensors and Bluetooth mesh for site supervisors.',
    price: 4299,
    compareAtPrice: 4999,
    category: 'Smart Mining Glasses',
    imageUrl: '/images/52d353be-ddcd-4bf5-a5d3-72763d22638f.jpg',
    stock: 24,
    badge: 'New',
    rating: 4.7,
    reviewCount: 41,
  },
  {
    name: 'Pulse Connect Mining Frame',
    description:
      'Lightweight carbon temples, swappable lens cartridges, and 12-hour battery for connected workflows.',
    price: 2899,
    category: 'Smart Mining Glasses',
    imageUrl: '/images/68ed65ac-6dec-4c97-bfff-7c92fef3f345.jpg',
    stock: 55,
    rating: 4.5,
    reviewCount: 67,
  },
  {
    name: 'Thick Rim Safety Goggles',
    description:
      'Heavy-duty thick rim frame with impact-resistant lenses. Ideal for welding bays and high-debris zones.',
    price: 1499,
    compareAtPrice: 1899,
    category: 'Safety Goggles',
    imageUrl: '/images/ffcc7a97-97cd-4899-b1d1-7d217430c7b6.jpg',
    stock: 76,
    badge: 'Bestseller',
    rating: 4.8,
    reviewCount: 152,
  },
  {
    name: 'Full Seal Safety Goggles',
    description:
      'Full peripheral seal against dust and splash. Compatible with hard hats and respirator straps.',
    price: 899,
    category: 'Safety Goggles',
    imageUrl: '/images/g.jpg',
    stock: 92,
    rating: 4.6,
    reviewCount: 98,
  },
  {
    name: 'Apex Seal Pro Goggles',
    description:
      'Wide field panoramic lens with anti-scratch coating and quick-release strap system.',
    price: 1199,
    compareAtPrice: 1499,
    category: 'Safety Goggles',
    imageUrl: '/images/89555cc8-a527-46d9-9791-6d907dc35223.jpg',
    stock: 64,
    badge: 'New',
    rating: 4.7,
    reviewCount: 53,
  },
  {
    name: 'StormGuard Chemical Goggles',
    description:
      'Chemical-splash rated seal with indirect venting and replaceable polycarbonate lenses.',
    price: 1099,
    category: 'Safety Goggles',
    imageUrl: '/images/pngwing.com - 2025-05-29T115058.969.png',
    stock: 58,
    rating: 4.5,
    reviewCount: 44,
  },
  {
    name: 'ClearView Wide Goggles',
    description:
      'Oversized lens for prescription insert compatibility. Anti-fog treatment for humid pits.',
    price: 749,
    category: 'Safety Goggles',
    imageUrl: '/images/pngwing.com - 2025-05-29T115244.011.png',
    stock: 110,
    rating: 4.4,
    reviewCount: 72,
  },
  {
    name: 'Half Rim Industrial Glasses',
    description:
      'Lightweight half-rim design for all-day wear. Anti-scratch coating and adjustable temple arms.',
    price: 999,
    compareAtPrice: 1299,
    category: 'Industrial Glasses',
    imageUrl: '/images/glllll.jpg',
    stock: 118,
    badge: 'Popular',
    rating: 4.7,
    reviewCount: 189,
  },
  {
    name: 'Blue Cut Office Shield',
    description:
      'Zero-power blue-cut lenses for control-room and surface office staff near operations.',
    price: 699,
    category: 'Industrial Glasses',
    imageUrl: '/images/black.png',
    stock: 145,
    rating: 4.5,
    reviewCount: 201,
  },
  {
    name: 'Forge Weld Shade 5',
    description:
      'Fixed shade welding eyewear with side shields and heat-resistant frame material.',
    price: 1599,
    compareAtPrice: 1999,
    category: 'Welding & Heat',
    imageUrl: '/images/d1629196-5a15-4dde-8549-bb3997058777.jpg',
    stock: 40,
    badge: 'Pro',
    rating: 4.8,
    reviewCount: 61,
  },
  {
    name: 'Inferno Auto-Darkening Glasses',
    description:
      'Auto-darkening filter for MIG/TIG transitions. Grind mode for surface prep.',
    price: 2799,
    category: 'Welding & Heat',
    imageUrl: '/images/pngwing.com - 2025-05-29T115317.090.png',
    stock: 28,
    badge: 'New',
    rating: 4.9,
    reviewCount: 37,
  },
  {
    name: 'HeatShield Wrap Industrial',
    description:
      'Wraparound frame for furnace and casting lines. High-temp nose pads included.',
    price: 1349,
    category: 'Welding & Heat',
    imageUrl: '/images/sec.jpg',
    stock: 36,
    rating: 4.6,
    reviewCount: 29,
  },
  {
    name: 'Crystal Office Blue Cut',
    description:
      'Clear fashion frame with 420nm blue filter for 10+ hour screen shifts.',
    price: 549,
    compareAtPrice: 799,
    category: 'Blue Light / Computer',
    imageUrl: '/images/first.jpg',
    stock: 180,
    badge: 'Value',
    rating: 4.5,
    reviewCount: 156,
  },
  {
    name: 'Focus Pro Gaming Shield',
    description:
      'Amber-tint gaming lenses reduce eye strain during monitoring and simulator ops.',
    price: 899,
    category: 'Blue Light / Computer',
    imageUrl: '/images/five.jpg',
    stock: 95,
    rating: 4.6,
    reviewCount: 88,
  },
  {
    name: 'Clarity Max Computer Glasses',
    description:
      'Ultra-light TR90 frame with hydrophobic coating. Includes microfiber pouch.',
    price: 649,
    category: 'Blue Light / Computer',
    imageUrl: '/images/six.jpg',
    stock: 130,
    rating: 4.4,
    reviewCount: 112,
  },
  {
    name: 'Site Commander Polarized',
    description:
      'Polarized sun lenses for open-pit glare. Meets industrial UV400 requirements.',
    price: 1899,
    compareAtPrice: 2299,
    category: 'Industrial Glasses',
    imageUrl: '/images/seven.jpg',
    stock: 52,
    rating: 4.7,
    reviewCount: 74,
  },
  {
    name: 'Ridge Titanium Safety Frame',
    description:
      'Titanium alloy frame with side impact guards. ANSI Z87.1 rated.',
    price: 2199,
    category: 'Industrial Glasses',
    imageUrl: '/images/eight.jpg',
    stock: 38,
    badge: 'Pro',
    rating: 4.8,
    reviewCount: 49,
  },
  {
    name: 'Compact Pit Crew Goggles',
    description:
      'Low-profile goggle for tight helmet clearance. Quick strap adjustment dial.',
    price: 849,
    category: 'Safety Goggles',
    imageUrl: '/images/four.jpg',
    stock: 88,
    rating: 4.5,
    reviewCount: 63,
  },
  {
    name: 'Onix Lite Surface Glasses',
    description:
      'Everyday surface operations frame with interchangeable clear and smoke lenses.',
    price: 1299,
    category: 'Industrial Glasses',
    imageUrl: '/images/thrd.jpg',
    stock: 72,
    rating: 4.6,
    reviewCount: 91,
  },
  {
    name: 'Zero Power Blue Cut Classic',
    description:
      'Computer glasses with classic rectangular styling for office and control towers.',
    price: 599,
    category: 'Blue Light / Computer',
    imageUrl: '/images/home.jpg',
    stock: 165,
    rating: 4.3,
    reviewCount: 134,
  },
  {
    name: 'Deep Shaft Smart Glasses S1',
    description:
      'Ruggedized smart frame with reinforced hinges for vertical shaft transport.',
    price: 3599,
    compareAtPrice: 4199,
    category: 'Smart Mining Glasses',
    imageUrl: '/images/WhatsApp Image 2025-05-27 at 1.11.09 PM.jpeg',
    stock: 20,
    badge: 'Limited',
    rating: 4.9,
    reviewCount: 22,
  },
];

module.exports = { PRODUCT_CATALOG };
